apply plugin: "com.android.application"

android {
    namespace "com.openatx.xtest.nova.uiautomator.test"
    compileSdk 36

    defaultConfig {
        applicationId "com.openatx.xtest.nova.uiautomator.test"
        minSdk 28
        targetSdk 34
        versionCode 7
        versionName "0.2.5-review-fix"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencyLocking {
    lockAllConfigurations()
}
