param([string[]]$Serial,[string]$OutputPath=(Join-Path $PSScriptRoot '..\reports\stateful-latest.json'))
$ErrorActionPreference='Stop';$repoRoot=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'));$fixturePackage='com.xtest.nova.fixture';$fixtureName='xtest-nova-validation.apk'
. (Join-Path $PSScriptRoot 'lib\device-validation-safety.ps1')
function Invoke-Adb([string]$DeviceSerial,[string[]]$Arguments){$output=& adb -s $DeviceSerial @Arguments;if($LASTEXITCODE -ne 0){throw "adb failed for ${DeviceSerial}: $Arguments"};return $output}
function Get-AgentPid([string]$DeviceSerial){$value=(& adb -s $DeviceSerial shell pidof xtest-nova-agent 2>$null|Out-String).Trim();if($LASTEXITCODE-ne 0){return ''};return $value}
function Stop-Agent([string]$DeviceSerial){foreach($value in((Get-AgentPid $DeviceSerial)-split'\s+')){if($value-match'^\d+$'){& adb -s $DeviceSerial shell kill $value 2>$null|Out-Null}}}
function Start-Agent([string]$DeviceSerial){Invoke-Adb $DeviceSerial @('shell','sh','-c',"'nohup /data/local/tmp/xtest-nova-agent server --no-popup >/data/local/tmp/xtest-nova-agent.log 2>&1 &'")|Out-Null}
function Add-Forward([string]$DeviceSerial){$value=(Invoke-Adb $DeviceSerial @('forward','tcp:0','tcp:7912')|Out-String).Trim();if($value -notmatch '^\d+$'){throw 'adb did not allocate a local port'};return [int]$value}
function Remove-Forward([string]$DeviceSerial,[int]$Port){if($Port-gt 0){& adb -s $DeviceSerial forward --remove "tcp:$Port" 2>$null|Out-Null}}
function Wait-Health([int]$Port){$deadline=[DateTime]::UtcNow.AddSeconds(12);do{try{return Invoke-RestMethod "http://127.0.0.1:$Port/v1/health" -TimeoutSec 3}catch{Start-Sleep -Milliseconds 250}}while([DateTime]::UtcNow-lt$deadline);throw 'Agent health timeout'}
function Get-Foreground([int]$Port){for($attempt=0;$attempt-lt 5;$attempt++){ $package=(Invoke-RestMethod "http://127.0.0.1:$Port/foregroundPkg" -TimeoutSec 10).package;if($package){return $package};Start-Sleep -Milliseconds 250};return ''}
function Get-HomePackage([string]$DeviceSerial){$lines=@(Invoke-Adb $DeviceSerial @('shell','cmd','package','resolve-activity','--brief','-a','android.intent.action.MAIN','-c','android.intent.category.HOME'));$component=$lines|Where-Object{$_-match'^[A-Za-z0-9_.]+/[A-Za-z0-9_.$]+$'}|Select-Object -Last 1;if($component){return ($component-split'/')[0]};return ''}
function Restore-Foreground([string]$DeviceSerial,[string]$Package){if($Package -notmatch '^[A-Za-z][A-Za-z0-9_]*(\.[A-Za-z0-9_]+)+$'){return $false};$lines=@(Invoke-Adb $DeviceSerial @('shell','cmd','package','resolve-activity','--brief',$Package));$activity=$lines|Where-Object{$_-match'^[A-Za-z0-9_.]+/[A-Za-z0-9_.$]+$'}|Select-Object -Last 1;if($activity){Invoke-Adb $DeviceSerial @('shell','am','start','-n',$activity)|Out-Null;return $true};return $false}
function Add-Step([System.Collections.Generic.List[object]]$Steps,[string]$Name,[bool]$Passed,[string]$Detail){$Steps.Add([pscustomobject]@{name=$Name;passed=$Passed;detail=$Detail})}
if(-not$Serial-or$Serial.Count-eq 0){$Serial=@(& adb devices|Select-Object -Skip 1|ForEach-Object{if($_-match'^([^\s]+)\s+device$'){$matches[1]}})};if($Serial.Count-eq 0){throw'No online Android devices found'}
$fixture="$repoRoot\dist\$fixtureName";if(-not(Test-Path -LiteralPath $fixture)){throw'Missing signed validation fixture; run build.ps1 with signing parameters'}
$results=@()
foreach($deviceSerial in $Serial){
    if($deviceSerial-notmatch'^[A-Za-z0-9._:-]+$'){throw"Invalid device serial: $deviceSerial"}
    $port=0;$owned=$false;$fixtureInstalled=$false;$originalForeground='';$originalIME='';$imeChanged=$false;$steps=[System.Collections.Generic.List[object]]::new();$result=[ordered]@{serial=$deviceSerial;sdk=0;abi='';version='';passed=$false;steps=$steps}
    try{
        $result.sdk=[int]((Invoke-Adb $deviceSerial @('shell','getprop','ro.build.version.sdk')|Out-String).Trim());$result.abi=(Invoke-Adb $deviceSerial @('shell','getprop','ro.product.cpu.abi')|Out-String).Trim()
        if(Get-AgentPid $deviceSerial){throw'Existing Agent found; refusing to replace it'}
        Assert-ValidationRemotePathsAbsent $deviceSerial @('/data/local/tmp/xtest-nova-agent','/data/local/tmp/xtest-nova-agent.log',"/data/local/tmp/apk/$fixtureName")
        Assert-ValidationRuntimeAbsent $deviceSerial
        $existingFixture=(& adb -s $deviceSerial shell pm path $fixturePackage 2>$null|Out-String).Trim();if($existingFixture){throw'Validation fixture is already installed; refusing to replace it'}
$agent=if($result.abi-match'^arm64'){"$repoRoot\dist\xtest-nova-agent-arm64"}elseif($result.abi-eq'armeabi-v7a'){"$repoRoot\dist\xtest-nova-agent-armv7"}else{throw"Unsupported ABI: $($result.abi)"}
        Invoke-Adb $deviceSerial @('push',$agent,'/data/local/tmp/xtest-nova-agent')|Out-Null;Invoke-Adb $deviceSerial @('shell','chmod','755','/data/local/tmp/xtest-nova-agent')|Out-Null;Start-Agent $deviceSerial;$owned=$true;$port=Add-Forward $deviceSerial;$health=Wait-Health $port;$result.version=$health.version;$base="http://127.0.0.1:$port";$originalForeground=Get-Foreground $port;if(-not$originalForeground){$originalForeground=Get-HomePackage $deviceSerial}
        Invoke-Adb $deviceSerial @('shell','mkdir','-p','/data/local/tmp/apk')|Out-Null;Invoke-Adb $deviceSerial @('push',$fixture,"/data/local/tmp/apk/$fixtureName")|Out-Null
        $installResponse=Invoke-WebRequest "$base/installLocalApk/$fixtureName" -Method Post -SkipHttpErrorCheck -TimeoutSec 30;$installBody=$installResponse.Content|ConvertFrom-Json;$fixtureSupported=$true
        if($installResponse.StatusCode -eq 200 -and $installBody.success){$fixtureInstalled=$true;Add-Step $steps 'fixture-install' $true 'installed through /installLocalApk'}elseif($installResponse.StatusCode -eq 500 -and $installBody.error -match 'INSTALL_FAILED_USER_RESTRICTED'){$fixtureSupported=$false;Add-Step $steps 'fixture-install-policy' $true 'blocked by device user-install policy; fixture flow skipped'}else{throw "Fixture install failed: HTTP $($installResponse.StatusCode) $($installBody.error)"}
        if($fixtureSupported){
            $info=Invoke-RestMethod "$base/packages/$fixturePackage/info" -TimeoutSec 15;if(-not$info.success-or$info.data.packageName-ne$fixturePackage-or$info.data.versionCode-ne 1){throw'Fixture package metadata mismatch'};Add-Step $steps 'fixture-info' $true 'package metadata verified'
            $session=Invoke-RestMethod "$base/session/$fixturePackage" -Method Post -TimeoutSec 30;if(-not$session.success){throw'Fixture session failed'};Start-Sleep -Milliseconds 500;$foreground=Get-Foreground $port;if($foreground-ne$fixturePackage){throw"Fixture is not foreground: $foreground"};Add-Step $steps 'fixture-session' $true $session.mainActivity
            $uninstalled=Invoke-RestMethod "$base/v1/apps/$fixturePackage" -Method Delete -TimeoutSec 30;if(-not$uninstalled.success){throw'Fixture uninstall endpoint did not report success'};$fixtureInstalled=$false;if((& adb -s $deviceSerial shell pm path $fixturePackage 2>$null|Out-String).Trim()){throw'Fixture remains installed'};Add-Step $steps 'fixture-uninstall' $true 'removed and verified absent'
            Start-Sleep -Milliseconds 300;$restored=((Get-Foreground $port)-eq$originalForeground);if(-not$restored){$null=Restore-Foreground $deviceSerial $originalForeground;Start-Sleep -Milliseconds 300;$restored=((Get-Foreground $port)-eq$originalForeground)};Add-Step $steps 'foreground-restore' $restored $originalForeground
        }
        $originalIME=(Invoke-Adb $deviceSerial @('shell','settings','get','secure','default_input_method')|Out-String).Trim();$enabled=@(Invoke-Adb $deviceSerial @('shell','ime','list','-s')|ForEach-Object{$_.Trim()}|Where-Object{$_})
        $safeIME=$enabled|Where-Object{$_-ne$originalIME-and($_-match'^(io\.appium\.settings|jp\.jun_nama\.test\.utf7ime|com\.android\.adbkeyboard)/')}|Select-Object -First 1
        if($safeIME){$changed=Invoke-RestMethod "$base/setIme" -Method Post -ContentType 'application/json' -Body(@{ime=$safeIME}|ConvertTo-Json) -TimeoutSec 15;if(-not$changed.success-or$changed.ime-ne$safeIME){throw'IME did not switch to the test input method'};$imeChanged=$true;$restoredIME=Invoke-RestMethod "$base/setIme" -Method Post -ContentType 'application/json' -Body(@{ime=$originalIME}|ConvertTo-Json) -TimeoutSec 15;$imeChanged=$false;if($restoredIME.ime-ne$originalIME){throw'IME did not restore'};Add-Step $steps 'ime-switch-restore' $true "$safeIME -> $originalIME"}else{Add-Step $steps 'ime-switch-restore' $true 'skipped: no approved test IME installed'}
        $before=Invoke-RestMethod "$base/services/uiautomator" -TimeoutSec 10
        if($before.running){$null=Invoke-RestMethod "$base/services/uiautomator" -Method Post -TimeoutSec 20;$null=Invoke-RestMethod "$base/services/uiautomator" -Method Delete -TimeoutSec 20;$after=Invoke-RestMethod "$base/services/uiautomator" -TimeoutSec 10;if(-not$after.running){throw'Nova stopped an externally owned UiAutomator service'};Add-Step $steps 'uiautomator-ownership' $true 'external service preserved'}else{$startResponse=Invoke-WebRequest "$base/services/uiautomator" -Method Post -SkipHttpErrorCheck -TimeoutSec 20;if($startResponse.StatusCode-eq 500-and$startResponse.Content-match'package is not installed'){Add-Step $steps 'uiautomator-lifecycle' $true 'skipped: server package is not installed'}elseif($startResponse.StatusCode-eq 200){$running=Invoke-RestMethod "$base/services/uiautomator" -TimeoutSec 10;if(-not$running.running){throw'owned UiAutomator did not start'};$null=Invoke-RestMethod "$base/services/uiautomator" -Method Delete -TimeoutSec 20;$after=Invoke-RestMethod "$base/services/uiautomator" -TimeoutSec 10;if($after.running){throw'owned UiAutomator did not stop'};Add-Step $steps 'uiautomator-lifecycle' $true 'owned start and stop verified'}else{throw"Unexpected UiAutomator start response: $($startResponse.StatusCode)"}}
        $result.passed=(@($steps|Where-Object{-not$_.passed}).Count-eq 0)
    }catch{Add-Step $steps 'harness' $false $_.Exception.Message;$result.passed=$false}
    finally{
        if($imeChanged-and$originalIME){& adb -s $deviceSerial shell ime set $originalIME 2>$null|Out-Null}
        if($fixtureInstalled){& adb -s $deviceSerial uninstall $fixturePackage 2>$null|Out-Null}
        if($originalForeground){try{$null=Restore-Foreground $deviceSerial $originalForeground}catch{}}
        & adb -s $deviceSerial shell rm -f "/data/local/tmp/apk/$fixtureName" 2>$null|Out-Null
        if($owned){Stop-Agent $deviceSerial;Remove-OwnedValidationRuntime $deviceSerial;& adb -s $deviceSerial shell rm -f /data/local/tmp/xtest-nova-agent /data/local/tmp/xtest-nova-agent.log 2>$null|Out-Null};Remove-Forward $deviceSerial $port
    }
    $results+=[pscustomobject]$result
}
$report=[ordered]@{schemaVersion='xtest-stateful/v1';generatedAt=[DateTime]::UtcNow.ToString('o');passed=(($results|Where-Object{-not$_.passed}).Count-eq 0);devices=$results};$directory=Split-Path -Parent $OutputPath;if($directory){New-Item -ItemType Directory -Force -Path $directory|Out-Null};$report|ConvertTo-Json -Depth 8|Set-Content -LiteralPath $OutputPath -Encoding utf8;$report|ConvertTo-Json -Depth 8;if(-not$report.passed){exit 1}
