param([string[]]$Serial,[string]$OutputPath=(Join-Path $PSScriptRoot '..\reports\m56-latest.json'))
$ErrorActionPreference='Stop';$repoRoot=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'));$fixturePackage='com.xtest.nova.fixture';$fixture="$repoRoot\dist\xtest-nova-validation.apk";$remoteAgent='/data/local/tmp/xtest-nova-agent';$remoteConfig='/data/local/tmp/xtest-nova-config.json'
. (Join-Path $PSScriptRoot 'lib\device-validation-safety.ps1')
function Invoke-Adb([string]$DeviceSerial,[string[]]$Arguments){$output=& adb -s $DeviceSerial @Arguments;if($LASTEXITCODE-ne 0){throw "adb failed for ${DeviceSerial}: $Arguments"};return $output}
function Get-AgentPid([string]$DeviceSerial){$value=(& adb -s $DeviceSerial shell pidof xtest-nova-agent 2>$null|Out-String).Trim();if($LASTEXITCODE-ne 0){return ''};return $value}
function Stop-Agent([string]$DeviceSerial){foreach($value in((Get-AgentPid $DeviceSerial)-split'\s+')){if($value-match'^\d+$'){& adb -s $DeviceSerial shell kill $value 2>$null|Out-Null}}}
function Add-Forward([string]$DeviceSerial,[int]$RemotePort){$value=(Invoke-Adb $DeviceSerial @('forward','tcp:0',"tcp:$RemotePort")|Out-String).Trim();if($value-notmatch'^\d+$'){throw 'adb did not allocate a local port'};return [int]$value}
function Wait-Health([int]$Port){$deadline=[DateTime]::UtcNow.AddSeconds(12);do{try{return Invoke-RestMethod "http://127.0.0.1:$Port/v1/health" -TimeoutSec 3}catch{Start-Sleep -Milliseconds 250}}while([DateTime]::UtcNow-lt$deadline);throw 'Agent health timeout'}
function Get-Foreground([int]$Port){try{return (Invoke-RestMethod "http://127.0.0.1:$Port/foregroundPkg" -TimeoutSec 10).package}catch{return ''}}
function Restore-Foreground([string]$DeviceSerial,[string]$Package){if($Package-notmatch'^[A-Za-z][A-Za-z0-9_]*(\.[A-Za-z0-9_]+)+$'){return};$activity=@(Invoke-Adb $DeviceSerial @('shell','cmd','package','resolve-activity','--brief',$Package)|Where-Object{$_-match'^[A-Za-z0-9_.]+/[A-Za-z0-9_.$]+$'}|Select-Object -Last 1);if($activity){Invoke-Adb $DeviceSerial @('shell','am','start','-n',$activity[0])|Out-Null}}
function Add-Step($Steps,[string]$Name,[bool]$Passed,[string]$Detail){$Steps.Add([pscustomobject]@{name=$Name;passed=$Passed;detail=$Detail})}
function Remove-Case([string]$DeviceSerial,[string]$Path){if($Path-match'^/sdcard/xtest-nova/com\.xtest\.nova\.fixture/Replay/[A-Za-z0-9._-]+/[0-9TZ.\-]+/case\.json$'){& adb -s $DeviceSerial shell rm -f $Path 2>$null|Out-Null;$directory=$Path.Substring(0,$Path.LastIndexOf('/'));& adb -s $DeviceSerial shell rmdir $directory 2>$null|Out-Null;$taskDirectory=$directory.Substring(0,$directory.LastIndexOf('/'));& adb -s $DeviceSerial shell rmdir $taskDirectory 2>$null|Out-Null}}
if(-not$Serial){$Serial=@(& adb devices|Select-Object -Skip 1|ForEach-Object{if($_-match'^([^\s]+)\s+device$'){$matches[1]}})};if(-not$Serial){throw 'No online Android devices found'};if(-not(Test-Path -LiteralPath $fixture)){throw 'Missing signed validation fixture'}
$results=@()
foreach($deviceSerial in $Serial){
    $port=0;$monitorPort=0;$owned=$false;$fixtureInstalled=$false;$originalForeground='';$casePath='';$steps=[System.Collections.Generic.List[object]]::new();$result=[ordered]@{serial=$deviceSerial;sdk=0;abi='';version='';passed=$false;steps=$steps}
    try{
        if($deviceSerial-notmatch'^[A-Za-z0-9._:-]+$'){throw 'Invalid serial'};$result.sdk=[int]((Invoke-Adb $deviceSerial @('shell','getprop','ro.build.version.sdk')|Out-String).Trim());$result.abi=(Invoke-Adb $deviceSerial @('shell','getprop','ro.product.cpu.abi')|Out-String).Trim()
        if(Get-AgentPid $deviceSerial){throw 'Existing Agent found; refusing to replace it'};Assert-ValidationRemotePathsAbsent $deviceSerial @($remoteAgent,'/data/local/tmp/xtest-nova-agent.log',$remoteConfig,"$remoteConfig.tmp");Assert-ValidationRuntimeAbsent $deviceSerial;if((& adb -s $deviceSerial shell pm path $fixturePackage 2>$null|Out-String).Trim()){throw 'Validation fixture already installed'}
$agent=if($result.abi-match'^arm64'){"$repoRoot\dist\xtest-nova-agent-arm64"}elseif($result.abi-eq'armeabi-v7a'){"$repoRoot\dist\xtest-nova-agent-armv7"}else{throw "Unsupported ABI: $($result.abi)"}
        Invoke-Adb $deviceSerial @('install','-r',$fixture)|Out-Null;$fixtureInstalled=$true;Invoke-Adb $deviceSerial @('push',$agent,$remoteAgent)|Out-Null;Invoke-Adb $deviceSerial @('shell','chmod','755',$remoteAgent)|Out-Null;Invoke-Adb $deviceSerial @('shell','sh','-c',"'nohup $remoteAgent server --no-popup >/data/local/tmp/xtest-nova-agent.log 2>&1 &'")|Out-Null;$owned=$true;$port=Add-Forward $deviceSerial 7912;$monitorPort=Add-Forward $deviceSerial 7890;$health=Wait-Health $port;$result.version=$health.version;$base="http://127.0.0.1:$port";$originalForeground=Get-Foreground $port
        $session=Invoke-RestMethod "$base/session/$fixturePackage" -Method Post -TimeoutSec 20;if(-not$session.success){throw 'Fixture session failed'};Start-Sleep -Milliseconds 500
        $popupConfig=@{autoClickByText=@(@{mainContentContains='目标应用样例';clickTarget="目标应用样例`n点击区域"});autoClickByResourceId=@();autoInputByHint=@();autoInputByResourceId=@()}|ConvertTo-Json -Depth 6;Invoke-RestMethod "$base/pushConfig" -Method Post -Headers $XTestControlHeaders -ContentType 'application/json' -Body $popupConfig -TimeoutSec 10|Out-Null;$popup=Invoke-RestMethod "$base/popupBoxAssistant" -Method Post -TimeoutSec 10;if(-not$popup.running){throw 'Popup Assistant did not start'}
        $deadline=[DateTime]::UtcNow.AddSeconds(6);$handled=$false;do{Start-Sleep -Milliseconds 500;$hierarchy=Invoke-RestMethod "$base/dump/hierarchy" -TimeoutSec 15;if($hierarchy.result-match'点击次数：1'){$handled=$true;break}}while([DateTime]::UtcNow-lt$deadline);$popup=Invoke-RestMethod "$base/popupBoxAssistant" -Method Delete -TimeoutSec 10;if(-not$handled-or$popup.running){throw 'Popup Assistant sample did not complete safely'};Add-Step $steps 'popup-safe-rule' $true 'unique fixture text matched, clicked, and stopped'
        $recordBody=@{requestId="m56-record-$deviceSerial";package=$fixturePackage;name='m56-safe-key'}|ConvertTo-Json;$recordResponse=Invoke-WebRequest "$base/v1/recordings" -Method Post -ContentType 'application/json' -Body $recordBody -SkipHttpErrorCheck -TimeoutSec 20;if($recordResponse.StatusCode-ne 202){throw "Recording start failed: HTTP $($recordResponse.StatusCode) $($recordResponse.Content)"};$recordState=$recordResponse.Content|ConvertFrom-Json;Start-Sleep -Milliseconds 300
        $recordHeaders=Get-XTestOwnedHeaders $recordState;Invoke-RestMethod "$base/v1/recordings/current/key" -Method Post -Headers $recordHeaders -ContentType 'application/json' -Body '{"keyCode":4}' -TimeoutSec 10|Out-Null;Invoke-RestMethod "$base/v1/recordings/current/assertions/screenshot" -Method Post -Headers $recordHeaders -ContentType 'application/json' -Body '{"maxHashDistance":16}' -TimeoutSec 20|Out-Null;$recordState=Stop-XTestOwnedExecution $base '/v1/recordings/current' $recordState 20;$casePath=$recordState.path;$case=Invoke-RestMethod "$base/v1/recordings/current/case" -TimeoutSec 10
        if(-not$case.integrity-or$case.actions.Count-ne 2){throw 'Recorded case is incomplete'};$validated=Invoke-RestMethod "$base/v1/replays/validate" -Method Post -ContentType 'application/json' -Body($case|ConvertTo-Json -Depth 20) -TimeoutSec 15;if(-not$validated.valid-or$validated.actions-ne 2){throw 'Recorded case validation failed'};Add-Step $steps 'record-seal-validate' $true "actions=$($validated.actions)"
        $replayBody=@{requestId="m56-replay-$deviceSerial";execute=$true;speed=4;resumeFrom=0;case=$case}|ConvertTo-Json -Depth 20;$replayResponse=Invoke-WebRequest "$base/v1/replays" -Method Post -ContentType 'application/json' -Body $replayBody -SkipHttpErrorCheck -TimeoutSec 20;if($replayResponse.StatusCode-ne 202){throw "Replay start failed: $($replayResponse.Content)"};$deadline=[DateTime]::UtcNow.AddSeconds(15);do{$replay=Invoke-RestMethod "$base/v1/replays/current" -TimeoutSec 10;if(-not$replay.running){break};Start-Sleep -Milliseconds 200}while([DateTime]::UtcNow-lt$deadline);if($replay.running-or$replay.stopReason-ne'completed'-or$replay.completedActions-ne 2){throw "Replay did not complete: $($replay.stopReason) $($replay.error)"};Add-Step $steps 'replay-end-to-end' $true '2/2 actions completed with foreground guard'
$streamJSON=go run (Join-Path $repoRoot 'agent\cmd\device-stream-check') -base $base -monitor "127.0.0.1:$monitorPort";if($LASTEXITCODE-ne 0){throw 'Stream checker failed'};$stream=$streamJSON|ConvertFrom-Json;Add-Step $steps 'stream-regression' $true "event=$($stream.appEventBytes) bytes, minicap=$($stream.minicapBytes) bytes, $($stream.rotation), monitor=$($stream.monitor)";$result.passed=$true
    }catch{Add-Step $steps 'harness' $false $_.Exception.Message}
    finally{if($port-gt 0){try{Invoke-RestMethod "http://127.0.0.1:$port/popupBoxAssistant" -Method Delete -TimeoutSec 5|Out-Null}catch{};try{Stop-XTestOwnedExecution "http://127.0.0.1:$port" '/v1/recordings/current' $null 5|Out-Null}catch{};try{Stop-XTestOwnedExecution "http://127.0.0.1:$port" '/v1/replays/current' $null 5|Out-Null}catch{}};if($casePath){Remove-Case $deviceSerial $casePath};if($fixtureInstalled){& adb -s $deviceSerial uninstall $fixturePackage 2>$null|Out-Null};if($originalForeground){try{Restore-Foreground $deviceSerial $originalForeground}catch{}};if($owned){Stop-Agent $deviceSerial;Remove-OwnedValidationRuntime $deviceSerial};& adb -s $deviceSerial shell rm -f $remoteAgent /data/local/tmp/xtest-nova-agent.log $remoteConfig "$remoteConfig.tmp" 2>$null|Out-Null;if($port-gt 0){& adb -s $deviceSerial forward --remove "tcp:$port" 2>$null|Out-Null};if($monitorPort-gt 0){& adb -s $deviceSerial forward --remove "tcp:$monitorPort" 2>$null|Out-Null}}
    $results+=[pscustomobject]$result
}
$report=[ordered]@{schemaVersion='xtest-m56-validation/v1';generatedAt=[DateTime]::UtcNow.ToString('o');passed=(($results|Where-Object{-not$_.passed}).Count-eq 0);devices=$results};$directory=Split-Path -Parent $OutputPath;if($directory){New-Item -ItemType Directory -Force -Path $directory|Out-Null};$report|ConvertTo-Json -Depth 8|Set-Content -LiteralPath $OutputPath -Encoding utf8;$report|ConvertTo-Json -Depth 8;if(-not$report.passed){exit 1}
