param([string[]]$Serial,[string]$DownloadUrl='https://example.com/',[string]$OutputPath=(Join-Path $PSScriptRoot '..\reports\delivery-media-latest.json'))
$ErrorActionPreference='Stop';$repoRoot=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'));$fixturePackage='com.xtest.nova.fixture';$fixture="$repoRoot\dist\xtest-nova-validation.apk";$downloadPath='/data/local/tmp/xtest-nova-public-download.html'
. (Join-Path $PSScriptRoot 'lib\device-validation-safety.ps1')
function Invoke-Adb([string]$DeviceSerial,[string[]]$Arguments){$output=& adb -s $DeviceSerial @Arguments;if($LASTEXITCODE-ne 0){throw "adb failed for ${DeviceSerial}: $Arguments"};return $output}
function Get-AgentPid([string]$DeviceSerial){$value=(& adb -s $DeviceSerial shell pidof xtest-nova-agent 2>$null|Out-String).Trim();if($LASTEXITCODE-ne 0){return ''};return $value}
function Stop-Agent([string]$DeviceSerial){foreach($value in((Get-AgentPid $DeviceSerial)-split'\s+')){if($value-match'^\d+$'){& adb -s $DeviceSerial shell kill $value 2>$null|Out-Null}}}
function Start-Agent([string]$DeviceSerial){Invoke-Adb $DeviceSerial @('shell','sh','-c',"'nohup /data/local/tmp/xtest-nova-agent server --no-popup >/data/local/tmp/xtest-nova-agent.log 2>&1 &'")|Out-Null}
function Add-Forward([string]$DeviceSerial){$value=(Invoke-Adb $DeviceSerial @('forward','tcp:0','tcp:7912')|Out-String).Trim();if($value-notmatch'^\d+$'){throw 'adb did not allocate a local port'};return [int]$value}
function Remove-Forward([string]$DeviceSerial,[int]$Port){if($Port-gt 0){& adb -s $DeviceSerial forward --remove "tcp:$Port" 2>$null|Out-Null}}
function Wait-Health([int]$Port){$deadline=[DateTime]::UtcNow.AddSeconds(12);do{try{return Invoke-RestMethod "http://127.0.0.1:$Port/v1/health" -TimeoutSec 3}catch{Start-Sleep -Milliseconds 250}}while([DateTime]::UtcNow-lt$deadline);throw 'Agent health timeout'}
function Add-Step([System.Collections.Generic.List[object]]$Steps,[string]$Name,[bool]$Passed,[string]$Detail){$Steps.Add([pscustomobject]@{name=$Name;passed=$Passed;detail=$Detail})}
function Remove-Video([string]$DeviceSerial,[string]$Path){
    $patterns=@(
        '^/sdcard/xtest-nova-screenrecords/[0-9TZ.\-]+/[^/]+\.mp4$',
        '^/sdcard/xtest-nova/[A-Za-z][A-Za-z0-9_]*(?:\.[A-Za-z][A-Za-z0-9_]*)+/ScreenRecord/[0-9]{8}_[0-9]{6}(?:_[0-9]+)?/[^/]+\.mp4$'
    )
    if(-not($patterns|Where-Object{$Path-match$_})){throw "Refusing to remove unexpected screenrecord path: $Path"}
    Invoke-Adb $DeviceSerial @('shell','rm','-f',$Path)|Out-Null
    & adb -s $DeviceSerial shell test -e $Path 2>$null
    if($LASTEXITCODE-eq 0){throw "Screenrecord cleanup did not remove: $Path"}
    $directory=$Path.Substring(0,$Path.LastIndexOf('/'))
    & adb -s $DeviceSerial shell rmdir $directory 2>$null|Out-Null
}
if(-not$Serial-or$Serial.Count-eq 0){$Serial=@(& adb devices|Select-Object -Skip 1|ForEach-Object{if($_-match'^([^\s]+)\s+device$'){$matches[1]}})};if($Serial.Count-eq 0){throw 'No online Android devices found'};if(-not(Test-Path -LiteralPath $fixture)){throw 'Missing signed validation fixture'}
$results=@()
foreach($deviceSerial in $Serial){
    $port=0;$owned=$false;$fixtureInstalled=$false;$recording=$false;$videos=@();$steps=[System.Collections.Generic.List[object]]::new();$result=[ordered]@{serial=$deviceSerial;sdk=0;abi='';version='';passed=$false;steps=$steps}
    try{
        if($deviceSerial-notmatch'^[A-Za-z0-9._:-]+$'){throw 'Invalid serial'};$result.sdk=[int]((Invoke-Adb $deviceSerial @('shell','getprop','ro.build.version.sdk')|Out-String).Trim());$result.abi=(Invoke-Adb $deviceSerial @('shell','getprop','ro.product.cpu.abi')|Out-String).Trim();if(Get-AgentPid $deviceSerial){throw 'Existing Agent found; refusing to replace it'};Assert-ValidationRemotePathsAbsent $deviceSerial @('/data/local/tmp/xtest-nova-agent','/data/local/tmp/xtest-nova-agent.log',$downloadPath);Assert-ValidationRuntimeAbsent $deviceSerial;if((& adb -s $deviceSerial shell pm path $fixturePackage 2>$null|Out-String).Trim()){throw 'Validation fixture already installed'}
$agent=if($result.abi-match'^arm64'){"$repoRoot\dist\xtest-nova-agent-arm64"}elseif($result.abi-eq'armeabi-v7a'){"$repoRoot\dist\xtest-nova-agent-armv7"}else{throw "Unsupported ABI: $($result.abi)"};Invoke-Adb $deviceSerial @('push',$agent,'/data/local/tmp/xtest-nova-agent')|Out-Null;Invoke-Adb $deviceSerial @('shell','chmod','755','/data/local/tmp/xtest-nova-agent')|Out-Null;Start-Agent $deviceSerial;$owned=$true;$port=Add-Forward $deviceSerial;$health=Wait-Health $port;$result.version=$health.version;$base="http://127.0.0.1:$port"
        $multipart=Invoke-WebRequest "$base/installApk" -Method Post -Form @{file=Get-Item -LiteralPath $fixture} -SkipHttpErrorCheck -TimeoutSec 40;$body=$multipart.Content|ConvertFrom-Json;if($multipart.StatusCode-eq 200-and$body.success){$fixtureInstalled=$true;Add-Step $steps 'multipart-install' $true "$($body.totalBytes) bytes"}elseif($multipart.StatusCode-eq 500-and$body.error-match'INSTALL_FAILED_USER_RESTRICTED'){Add-Step $steps 'multipart-install-policy' $true 'blocked by device user-install policy'}else{throw "multipart install failed: HTTP $($multipart.StatusCode) $($body.error)"};if($fixtureInstalled){$removed=Invoke-RestMethod "$base/v1/apps/$fixturePackage" -Method Delete -TimeoutSec 30;if(-not$removed.success){throw 'fixture uninstall failed'};$fixtureInstalled=$false;Add-Step $steps 'multipart-cleanup' $true 'fixture removed'}
        $taskID=(Invoke-WebRequest "$base/download" -Method Post -Body @{url=$DownloadUrl;filepath=$downloadPath;mode='0644'} -TimeoutSec 15).Content.Trim();if($taskID-notmatch'^[a-f0-9]{24}$'){throw "invalid download task id: $taskID"};$deadline=[DateTime]::UtcNow.AddSeconds(45);do{$task=Invoke-RestMethod "$base/download/$taskID" -TimeoutSec 10;if($task.status-in@('success','failure','canceled')){break};Start-Sleep -Milliseconds 300}while([DateTime]::UtcNow-lt$deadline);if($task.status-ne'success'-or$task.copiedSize-le 0){throw "public download failed: $($task.status) $($task.error)"};$remoteSize=[int64]((Invoke-Adb $deviceSerial @('shell','stat','-c','%s',$downloadPath)|Out-String).Trim());if($remoteSize-ne$task.copiedSize){throw 'downloaded file size mismatch'};Add-Step $steps 'public-https-download' $true "$remoteSize bytes"
        $start=Invoke-WebRequest "$base/screenrecord" -Method Post -TimeoutSec 15;if($start.StatusCode-ne 200){throw 'screenrecord did not start'};$recording=$true;Start-Sleep -Seconds 5;$stopped=Invoke-RestMethod "$base/screenrecord" -Method Put -TimeoutSec 20;$recording=$false;$videos=@($stopped.videos);if($videos.Count-ne 1){throw "unexpected video count: $($videos.Count)"};$video=$videos[0];$size=[int64]((Invoke-Adb $deviceSerial @('shell','stat','-c','%s',$video)|Out-String).Trim());if($size-le 1024){throw "recording is too small: $size"};Add-Step $steps 'screenrecord-lifecycle' $true "$size bytes";Remove-Video $deviceSerial $video;$videos=@();Add-Step $steps 'screenrecord-cleanup' $true 'video and session directory removed'
        $result.passed=(@($steps|Where-Object{-not$_.passed}).Count-eq 0)
    }catch{Add-Step $steps 'harness' $false $_.Exception.Message;$result.passed=$false}
    finally{if($recording-and$port-gt 0){try{$stopped=Invoke-RestMethod "http://127.0.0.1:$port/screenrecord" -Method Put -TimeoutSec 20;$videos=@($stopped.videos)}catch{}};foreach($video in $videos){Remove-Video $deviceSerial $video};if($fixtureInstalled){& adb -s $deviceSerial uninstall $fixturePackage 2>$null|Out-Null};& adb -s $deviceSerial shell rm -f $downloadPath 2>$null|Out-Null;if($owned){Stop-Agent $deviceSerial;Remove-OwnedValidationRuntime $deviceSerial;& adb -s $deviceSerial shell rm -f /data/local/tmp/xtest-nova-agent /data/local/tmp/xtest-nova-agent.log 2>$null|Out-Null};Remove-Forward $deviceSerial $port}
    $results+=[pscustomobject]$result
}
$report=[ordered]@{schemaVersion='xtest-delivery-media/v1';generatedAt=[DateTime]::UtcNow.ToString('o');downloadUrl=$DownloadUrl;passed=(($results|Where-Object{-not$_.passed}).Count-eq 0);devices=$results};$directory=Split-Path -Parent $OutputPath;if($directory){New-Item -ItemType Directory -Force -Path $directory|Out-Null};$report|ConvertTo-Json -Depth 8|Set-Content -LiteralPath $OutputPath -Encoding utf8;$report|ConvertTo-Json -Depth 8;if(-not$report.passed){exit 1}
